
# Yaml Axis Plugin
# https://wiki.jenkins-ci.org/display/JENKINS/Yaml+Axis+Plugin
# This is a generated file produced by scripts/pr-ci-matrix.rb.

xcode_version: 
 - 10.0
 - 10.1
 - 10.2.1
 - 10.3
 - 11.1
 - 11.2
target: 
 - docs
 - swiftlint
 - osx
 - osx-encryption
 - osx-object-server
 - ios-static
 - ios-dynamic
 - watchos
 - tvos
 - ios-swift
 - osx-swift
 - tvos-swift
 - cocoapods-osx
 - cocoapods-ios
 - cocoapods-watchos
 - swiftpm
configuration: 
 - Debug
 - Release

exclude:

  - xcode_version: 10.0
    target: docs
    configuration: Debug

  - xcode_version: 10.0
    target: docs
    configuration: Release

  - xcode_version: 10.1
    target: docs
    configuration: Debug

  - xcode_version: 10.1
    target: docs
    configuration: Release

  - xcode_version: 10.2.1
    target: docs
    configuration: Debug

  - xcode_version: 10.2.1
    target: docs
    configuration: Release

  - xcode_version: 10.3
    target: docs
    configuration: Debug

  - xcode_version: 10.3
    target: docs
    configuration: Release

  - xcode_version: 11.1
    target: docs
    configuration: Debug

  - xcode_version: 11.1
    target: docs
    configuration: Release

  - xcode_version: 11.2
    target: docs
    configuration: Debug

  - xcode_version: 10.0
    target: swiftlint
    configuration: Debug

  - xcode_version: 10.0
    target: swiftlint
    configuration: Release

  - xcode_version: 10.1
    target: swiftlint
    configuration: Debug

  - xcode_version: 10.1
    target: swiftlint
    configuration: Release

  - xcode_version: 10.2.1
    target: swiftlint
    configuration: Debug

  - xcode_version: 10.2.1
    target: swiftlint
    configuration: Release

  - xcode_version: 10.3
    target: swiftlint
    configuration: Debug

  - xcode_version: 10.3
    target: swiftlint
    configuration: Release

  - xcode_version: 11.1
    target: swiftlint
    configuration: Debug

  - xcode_version: 11.1
    target: swiftlint
    configuration: Release

  - xcode_version: 11.2
    target: swiftlint
    configuration: Debug

  - xcode_version: 10.0
    target: osx-encryption
    configuration: Debug

  - xcode_version: 10.1
    target: osx-encryption
    configuration: Debug

  - xcode_version: 10.1
    target: osx-encryption
    configuration: Release

  - xcode_version: 10.2.1
    target: osx-encryption
    configuration: Debug

  - xcode_version: 10.2.1
    target: osx-encryption
    configuration: Release

  - xcode_version: 10.3
    target: osx-encryption
    configuration: Debug

  - xcode_version: 10.3
    target: osx-encryption
    configuration: Release

  - xcode_version: 11.1
    target: osx-encryption
    configuration: Debug

  - xcode_version: 11.1
    target: osx-encryption
    configuration: Release

  - xcode_version: 11.2
    target: osx-encryption
    configuration: Debug

  - xcode_version: 10.0
    target: osx-object-server
    configuration: Debug

  - xcode_version: 10.1
    target: osx-object-server
    configuration: Debug

  - xcode_version: 10.1
    target: osx-object-server
    configuration: Release

  - xcode_version: 10.2.1
    target: osx-object-server
    configuration: Debug

  - xcode_version: 10.2.1
    target: osx-object-server
    configuration: Release

  - xcode_version: 10.3
    target: osx-object-server
    configuration: Debug

  - xcode_version: 10.3
    target: osx-object-server
    configuration: Release

  - xcode_version: 11.1
    target: osx-object-server
    configuration: Debug

  - xcode_version: 11.1
    target: osx-object-server
    configuration: Release

  - xcode_version: 11.2
    target: osx-object-server
    configuration: Debug

  - xcode_version: 10.0
    target: ios-static
    configuration: Debug

  - xcode_version: 10.1
    target: ios-static
    configuration: Debug

  - xcode_version: 10.2.1
    target: ios-static
    configuration: Debug

  - xcode_version: 10.3
    target: ios-static
    configuration: Debug

  - xcode_version: 11.1
    target: ios-static
    configuration: Debug

  - xcode_version: 10.0
    target: ios-dynamic
    configuration: Debug

  - xcode_version: 10.1
    target: ios-dynamic
    configuration: Debug

  - xcode_version: 10.2.1
    target: ios-dynamic
    configuration: Debug

  - xcode_version: 10.3
    target: ios-dynamic
    configuration: Debug

  - xcode_version: 11.1
    target: ios-dynamic
    configuration: Debug

  - xcode_version: 10.0
    target: watchos
    configuration: Debug

  - xcode_version: 10.1
    target: watchos
    configuration: Debug

  - xcode_version: 10.2.1
    target: watchos
    configuration: Debug

  - xcode_version: 10.3
    target: watchos
    configuration: Debug

  - xcode_version: 11.1
    target: watchos
    configuration: Debug

  - xcode_version: 10.0
    target: tvos
    configuration: Debug

  - xcode_version: 10.1
    target: tvos
    configuration: Debug

  - xcode_version: 10.2.1
    target: tvos
    configuration: Debug

  - xcode_version: 10.3
    target: tvos
    configuration: Debug

  - xcode_version: 11.1
    target: tvos
    configuration: Debug

  - xcode_version: 10.0
    target: ios-swift
    configuration: Debug

  - xcode_version: 10.1
    target: ios-swift
    configuration: Debug

  - xcode_version: 10.2.1
    target: ios-swift
    configuration: Debug

  - xcode_version: 10.3
    target: ios-swift
    configuration: Debug

  - xcode_version: 11.1
    target: ios-swift
    configuration: Debug

  - xcode_version: 10.0
    target: osx-swift
    configuration: Debug

  - xcode_version: 10.1
    target: osx-swift
    configuration: Debug

  - xcode_version: 10.2.1
    target: osx-swift
    configuration: Debug

  - xcode_version: 10.3
    target: osx-swift
    configuration: Debug

  - xcode_version: 11.1
    target: osx-swift
    configuration: Debug

  - xcode_version: 10.0
    target: tvos-swift
    configuration: Debug

  - xcode_version: 10.1
    target: tvos-swift
    configuration: Debug

  - xcode_version: 10.2.1
    target: tvos-swift
    configuration: Debug

  - xcode_version: 10.3
    target: tvos-swift
    configuration: Debug

  - xcode_version: 11.1
    target: tvos-swift
    configuration: Debug

  - xcode_version: 10.0
    target: cocoapods-osx
    configuration: Debug

  - xcode_version: 10.1
    target: cocoapods-osx
    configuration: Debug

  - xcode_version: 10.2.1
    target: cocoapods-osx
    configuration: Debug

  - xcode_version: 10.3
    target: cocoapods-osx
    configuration: Debug

  - xcode_version: 11.1
    target: cocoapods-osx
    configuration: Debug

  - xcode_version: 11.2
    target: cocoapods-osx
    configuration: Debug

  - xcode_version: 10.0
    target: cocoapods-ios
    configuration: Debug

  - xcode_version: 10.1
    target: cocoapods-ios
    configuration: Debug

  - xcode_version: 10.2.1
    target: cocoapods-ios
    configuration: Debug

  - xcode_version: 10.3
    target: cocoapods-ios
    configuration: Debug

  - xcode_version: 11.1
    target: cocoapods-ios
    configuration: Debug

  - xcode_version: 11.2
    target: cocoapods-ios
    configuration: Debug

  - xcode_version: 10.0
    target: cocoapods-watchos
    configuration: Debug

  - xcode_version: 10.1
    target: cocoapods-watchos
    configuration: Debug

  - xcode_version: 10.2.1
    target: cocoapods-watchos
    configuration: Debug

  - xcode_version: 10.3
    target: cocoapods-watchos
    configuration: Debug

  - xcode_version: 11.1
    target: cocoapods-watchos
    configuration: Debug

  - xcode_version: 11.2
    target: cocoapods-watchos
    configuration: Debug

  - xcode_version: 10.0
    target: swiftpm
    configuration: Debug

  - xcode_version: 10.0
    target: swiftpm
    configuration: Release

  - xcode_version: 10.1
    target: swiftpm
    configuration: Debug

  - xcode_version: 10.1
    target: swiftpm
    configuration: Release

  - xcode_version: 10.2.1
    target: swiftpm
    configuration: Debug

  - xcode_version: 10.2.1
    target: swiftpm
    configuration: Release

  - xcode_version: 10.3
    target: swiftpm
    configuration: Debug

  - xcode_version: 11.1
    target: swiftpm
    configuration: Debug

  - xcode_version: 11.1
    target: swiftpm
    configuration: Release

  - xcode_version: 11.2
    target: swiftpm
    configuration: Debug
