<?php

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

// Example data
// $id = "3";
$id = $_GET['id'];

curl_setopt($ch, CURLOPT_URL, "http://public.dir-massif-central.magsys-services.net/index.php/camera/ajaxRefresh");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "cam_id=$id&cam_width=undefined&cam_height=undefined&cam_frame=0");
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();
$headers[] = "Pragma: no-cache";
$headers[] = "Origin: http://public.dir-massif-central.magsys-services.net";
$headers[] = "Accept-Encoding: gzip, deflate";
$headers[] = "Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,es;q=0.6,de;q=0.5,cs;q=0.4,pt;q=0.3,la;q=0.2";
$headers[] = "Content-Type: application/x-www-form-urlencoded; charset=UTF-8";
$headers[] = "Accept: application/json, text/javascript, /; q=0.01";
$headers[] = "Cache-Control: no-cache";
$headers[] = "Referer: http://public.dir-massif-central.magsys-services.net";
$headers[] = "Connection: keep-alive";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error: ' . curl_error($ch);
} else {
    // http://public.dir-massif-central.magsys-services.net/stream/LES_CHAZES/20180212/1_235918.jpg
    preg_match('/.+cam_previous = "(?P<filename>.+)";/', $result, $matches);
    $filename = $matches['filename'];
    $url = "http://public.dir-massif-central.magsys-services.net/$filename";

    header("content-type: image/jpeg");
    echo file_get_contents($url);
}

curl_close ($ch);